version: '3.8'
services:
  app:
    build: .
    container_name: python_web_app
    ports:
      - "5000:5000"
    networks:
      - custom_bridge

networks:
  custom_bridge:
    driver: bridge
