apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-minikube-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-minikube-app
  template:
    metadata:
      labels:
        app: flask-minikube-app
    spec:
      containers:
      - name: flask-minikube-app
        image: sj3618/flask-minikube-app:v1
        ports:
        - containerPort: 5000
