apiVersion: v1
kind: Service
metadata:
  name: flask-minikube-service
spec:
  type: NodePort
  selector:
    app: flask-minikube-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30077
